-- =============================================================================
-- myBJJ V1 — SEED (Phase 3a)
-- Generated from index.html UNITS / STAFF / STUDENTS / PROMOTION_LOG /
-- EVENTS / SCHED. Run AFTER 04_schema_v2.sql. Safe to re-run (UPSERT).
-- =============================================================================

-- Counts: units=15 staff=3 students=52 promotions=7 events=5 sched=4

-- 1) Units
insert into public.units (legacy_id, name, country, city, address, active) values
  ('nb', 'Neutral Bay', 'AU', 'Sydney', '120 Military Rd, Neutral Bay NSW', true),
  ('hq', 'Camperdown HQ', 'AU', 'Sydney', '119-125 Parramatta Rd, Camperdown NSW', true),
  ('lid', 'Lidcombe', 'AU', 'Sydney', '19/21 East St, Lidcombe NSW', true),
  ('7h', 'Seven Hills', 'AU', 'Sydney', '36 Abbott Rd, Seven Hills NSW', true),
  ('mud', 'Mudgee', 'AU', 'Mudgee', '64 Sydney Rd, Mudgee NSW', true),
  ('cc', 'Central Coast', 'AU', 'Woy Woy', '27 Bowden Rd, Woy Woy NSW', true),
  ('mel', 'Melbourne', 'AU', 'Melbourne', 'Coming soon', false),
  ('nls', 'Nelson', 'NZ', 'Nelson', '76 Vanguard St, Nelson NZ', true),
  ('wgr', 'Whangarei', 'NZ', 'Whangarei', '273 Port Rd, Whangarei NZ', true),
  ('jpn', 'Japan HQ', 'JP', 'Aichi', 'Toyoake Danchi, Aichi', true),
  ('ngo', 'Nagoya', 'JP', 'Nagoya', 'Motoshio Community Centre, Nagoya', true),
  ('okz', 'Okazaki', 'JP', 'Okazaki', 'Idashin-machi 9-1, Okazaki', true),
  ('kor', 'Busan (Sajik)', 'KR', 'Busan', 'Sajikbuk-ro, Dongnae-gu, Busan', true),
  ('kor2', 'Busan (Myeongji)', 'KR', 'Busan', 'Myeongjigukje 2-ro, Gangseo-gu, Busan', true),
  ('usa', 'USA', 'US', 'TBD', 'Coming soon', false)
on conflict (legacy_id) do update set
  name=excluded.name, country=excluded.country, city=excluded.city,
  address=excluded.address, active=excluded.active;

-- 2) Staff (depends on units)
insert into public.staff (legacy_id, full_name, belt, degree, role_title, initials, total_classes, journey, feedback, unit_id) values
  ('mario_s', 'Prof. Mario', 'black', 5, 'Head Professor', 'MY', 0, '[{"belt":"black","label":"Black belt","date":"Jan 2005","classes":0,"done":true},{"belt":"black","label":"1st degree","date":"Jun 2008","classes":0,"done":true},{"belt":"black","label":"2nd degree","date":"Mar 2012","classes":0,"done":true},{"belt":"black","label":"3rd degree","date":"Sep 2016","classes":0,"done":true},{"belt":"black","label":"4th degree","date":"Jan 2021","classes":0,"done":true},{"belt":"black","label":"5th degree","date":"Mar 2025","classes":0,"done":true,"current":true},{"belt":"black","label":"6th degree","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('felipe_s', 'Prof. Felipe', 'black', 1, 'Professor', 'FP', 0, '[{"belt":"white","label":"Started BJJ","date":"Mar 2010","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Sep 2012","classes":0,"done":true},{"belt":"purple","label":"Purple belt","date":"Jun 2015","classes":0,"done":true},{"belt":"brown","label":"Brown belt","date":"Apr 2020","classes":0,"done":true},{"belt":"brown","label":"Brown — 3rd stripe","date":"Oct 2025","classes":0,"done":true,"current":true},{"belt":"black","label":"Black belt promotion","date":null,"classes":null,"done":false}]', '[{"ins":"Prof. Mario","date":"Feb 2026","text":"Felipe is showing strong leadership in kids classes. Technically ready — working on the mat presence and teaching consistency before black belt."}]', (select id from public.units where legacy_id='nb')),
  ('john_s', 'Prof. John', 'black', 1, 'Professor', 'JN2', 0, '[{"belt":"white","label":"Started BJJ","date":"Jan 2009","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Aug 2011","classes":0,"done":true},{"belt":"purple","label":"Purple belt","date":"Mar 2014","classes":0,"done":true},{"belt":"brown","label":"Brown belt","date":"Nov 2018","classes":0,"done":true},{"belt":"black","label":"Black belt","date":"Jun 2022","classes":0,"done":true},{"belt":"black","label":"1st degree","date":"Jan 2026","classes":0,"done":true,"current":true},{"belt":"black","label":"2nd degree","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='hq'))
on conflict (legacy_id) do update set
  full_name=excluded.full_name, belt=excluded.belt, degree=excluded.degree,
  role_title=excluded.role_title, initials=excluded.initials,
  total_classes=excluded.total_classes, journey=excluded.journey,
  feedback=excluded.feedback, unit_id=excluded.unit_id;

-- 3) Students (depends on units)
insert into public.students (legacy_id, full_name, belt, degree, prog, total, gi_classes, nogi_classes, grade, gi_grade, initials, has_gi, gender, journey, feedback, unit_id) values
  ('ff', 'Felipe F.', 'white', 4, 'adult', 87, 52, 35, 37, 22, 'FF', true, 'm', '[{"label":"Transferred from Academia Gracie SP","date":"Jan 2022","classes":null,"done":true,"xfer":true,"prev":"Academia Gracie São Paulo"},{"belt":"white","label":"Started at myBJJ","date":"Mar 2023","classes":0,"done":true},{"belt":"white","label":"White — 1st stripe","date":"Jun 2023","classes":18,"done":true},{"belt":"white","label":"White — 2nd stripe","date":"Oct 2023","classes":40,"done":true},{"belt":"white","label":"White — 3rd stripe","date":"Feb 2024","classes":64,"done":true},{"belt":"white","label":"White — 4th stripe","date":"Sep 2024","classes":87,"done":true,"current":true},{"belt":"blue","label":"Blue belt promotion","date":null,"classes":null,"done":false}]', '[{"ins":"Prof. Mario","date":"Mar 2026","text":"Great improvement in guard retention. Work on hip movement — mobility drills will help."},{"ins":"Prof. Felipe","date":"Feb 2026","text":"Good consistency. Focus on base when opponent stands in guard."}]', (select id from public.units where legacy_id='nb')),
  ('jp', 'Johnpatrick M.', 'blue', 2, 'adult', 280, 220, 60, 60, 55, 'JM', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jan 2020","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Jun 2022","classes":180,"done":true},{"belt":"blue","label":"Blue — 2nd stripe","date":"Mar 2025","classes":260,"done":true,"current":true},{"belt":"blue","label":"Blue — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('lp', 'Luke P.', 'white', 3, 'adult', 95, 70, 25, 35, 28, 'LP', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Aug 2023","classes":0,"done":true},{"belt":"white","label":"White — 3rd stripe","date":"Jun 2025","classes":80,"done":true,"current":true},{"belt":"white","label":"White — 4th stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('dig', 'Diggaj', 'blue', 1, 'adult', 210, 160, 50, 50, 45, 'DG', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Mar 2021","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Sep 2023","classes":160,"done":true},{"belt":"blue","label":"Blue — 1st stripe","date":"Dec 2024","classes":195,"done":true,"current":true},{"belt":"blue","label":"Blue — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('tom', 'Tommy', 'white', 2, 'adult', 55, 40, 15, 22, 18, 'TM', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jan 2025","classes":0,"done":true},{"belt":"white","label":"White — 2nd stripe","date":"Oct 2025","classes":38,"done":true,"current":true},{"belt":"white","label":"White — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('all', 'Allen', 'blue', 3, 'adult', 350, 290, 60, 72, 68, 'AL', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jun 2019","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Jan 2022","classes":180,"done":true},{"belt":"blue","label":"Blue — 3rd stripe","date":"Aug 2025","classes":330,"done":true,"current":true},{"belt":"blue","label":"Blue — 4th stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('tim', 'Tim', 'white', 1, 'adult', 28, 20, 8, 28, 20, 'TI', false, 'm', '[{"belt":"white","label":"Started BJJ","date":"Nov 2025","classes":0,"done":true},{"belt":"white","label":"White — 1st stripe","date":"Jan 2026","classes":20,"done":true,"current":true},{"belt":"white","label":"White — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('chr', 'Chris', 'purple', 1, 'adult', 420, 360, 60, 85, 80, 'CR', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Feb 2018","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Jun 2020","classes":180,"done":true},{"belt":"purple","label":"Purple belt","date":"Mar 2024","classes":380,"done":true},{"belt":"purple","label":"Purple — 1st stripe","date":"Jan 2026","classes":410,"done":true,"current":true},{"belt":"purple","label":"Purple — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('anna', 'Anna', 'white', 2, 'adult', 48, 38, 10, 22, 18, 'AN', true, 'f', '[{"belt":"white","label":"Started BJJ","date":"May 2025","classes":0,"done":true},{"belt":"white","label":"White — 2nd stripe","date":"Jan 2026","classes":38,"done":true,"current":true},{"belt":"white","label":"White — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('ped', 'Pedro', 'blue', 2, 'adult', 190, 145, 45, 45, 40, 'PE', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Sep 2021","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Apr 2024","classes":150,"done":true},{"belt":"blue","label":"Blue — 2nd stripe","date":"Feb 2026","classes":185,"done":true,"current":true},{"belt":"blue","label":"Blue — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('jac', 'Jackson O.', 'blue', 2, 'adult', 310, 250, 60, 65, 58, 'JO', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Sep 2021","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Mar 2023","classes":140,"done":true},{"belt":"blue","label":"Blue — 2nd stripe","date":"Nov 2024","classes":290,"done":true,"current":true},{"belt":"blue","label":"Blue — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('cia', 'Ciaron', 'white', 3, 'adult', 130, 95, 35, 38, 30, 'CI', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Mar 2023","classes":0,"done":true},{"belt":"white","label":"White — 3rd stripe","date":"Sep 2025","classes":110,"done":true,"current":true},{"belt":"white","label":"White — 4th stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('dar', 'Darcy', 'white', 1, 'adult', 32, 25, 7, 32, 25, 'DC', false, 'm', '[{"belt":"white","label":"Started BJJ","date":"Sep 2025","classes":0,"done":true},{"belt":"white","label":"White — 1st stripe","date":"Jan 2026","classes":22,"done":true,"current":true},{"belt":"white","label":"White — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('kev', 'Kevin T.', 'blue', 1, 'adult', 185, 140, 45, 48, 42, 'KT', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jun 2021","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Nov 2023","classes":145,"done":true},{"belt":"blue","label":"Blue — 1st stripe","date":"Oct 2025","classes":175,"done":true,"current":true},{"belt":"blue","label":"Blue — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('brk', 'Brock', 'blue', 3, 'adult', 390, 320, 70, 80, 75, 'BR', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jan 2019","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Aug 2021","classes":160,"done":true},{"belt":"blue","label":"Blue — 3rd stripe","date":"Jun 2025","classes":370,"done":true,"current":true},{"belt":"blue","label":"Blue — 4th stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('hea', 'Heather', 'white', 2, 'adult', 62, 48, 14, 28, 22, 'HE', true, 'f', '[{"belt":"white","label":"Started BJJ","date":"Feb 2025","classes":0,"done":true},{"belt":"white","label":"White — 2nd stripe","date":"Dec 2025","classes":45,"done":true,"current":true},{"belt":"white","label":"White — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('eri', 'Erika', 'blue', 1, 'adult', 195, 150, 45, 52, 46, 'ER', true, 'f', '[{"belt":"white","label":"Started BJJ","date":"Apr 2021","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Jan 2024","classes":155,"done":true},{"belt":"blue","label":"Blue — 1st stripe","date":"Nov 2025","classes":185,"done":true,"current":true},{"belt":"blue","label":"Blue — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('lia', 'Liam G.', 'white', 4, 'adult', 120, 88, 32, 38, 32, 'LG', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"May 2022","classes":0,"done":true},{"belt":"white","label":"White — 4th stripe","date":"Oct 2025","classes":110,"done":true,"current":true},{"belt":"blue","label":"Blue belt","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('ben', 'Benji', 'white', 1, 'adult', 22, 16, 6, 22, 16, 'BJ', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jan 2026","classes":0,"done":true},{"belt":"white","label":"White — 1st stripe","date":"Mar 2026","classes":16,"done":true,"current":true},{"belt":"white","label":"White — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('aar', 'Aaron', 'purple', 2, 'adult', 480, 400, 80, 90, 85, 'AC', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Mar 2018","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Sep 2020","classes":160,"done":true},{"belt":"purple","label":"Purple belt","date":"Apr 2024","classes":420,"done":true},{"belt":"purple","label":"Purple — 2nd stripe","date":"Dec 2025","classes":468,"done":true,"current":true},{"belt":"purple","label":"Purple — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('mit', 'Mitchell', 'blue', 2, 'adult', 240, 190, 50, 58, 52, 'MC', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jul 2021","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Feb 2024","classes":180,"done":true},{"belt":"blue","label":"Blue — 2nd stripe","date":"Jan 2026","classes":230,"done":true,"current":true},{"belt":"blue","label":"Blue — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('lee', 'Lee M.', 'white', 3, 'adult', 88, 65, 23, 32, 26, 'LM', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jun 2023","classes":0,"done":true},{"belt":"white","label":"White — 3rd stripe","date":"Jan 2026","classes":76,"done":true,"current":true},{"belt":"white","label":"White — 4th stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('jam', 'James P.', 'blue', 1, 'adult', 210, 175, 35, 55, 50, 'JP2', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jan 2022","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Jun 2023","classes":120,"done":true},{"belt":"blue","label":"Blue — 1st stripe","date":"Jan 2024","classes":165,"done":true,"current":true},{"belt":"blue","label":"Blue — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('adm', 'Adam', 'white', 2, 'adult', 55, 40, 15, 22, 18, 'AD', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jan 2025","classes":0,"done":true},{"belt":"white","label":"White — 2nd stripe","date":"Oct 2025","classes":38,"done":true,"current":true},{"belt":"white","label":"White — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('jay', 'Jay C.', 'blue', 2, 'adult', 260, 205, 55, 62, 56, 'JC', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Oct 2020","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"May 2023","classes":175,"done":true},{"belt":"blue","label":"Blue — 2nd stripe","date":"Dec 2025","classes":248,"done":true,"current":true},{"belt":"blue","label":"Blue — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('nic', 'Nick N.', 'white', 2, 'adult', 68, 50, 18, 28, 22, 'NN', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jul 2024","classes":0,"done":true},{"belt":"white","label":"White — 2nd stripe","date":"Jan 2026","classes":45,"done":true,"current":true},{"belt":"white","label":"White — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('rly', 'Riley W.', 'white', 1, 'adult', 35, 28, 7, 35, 28, 'RW', false, 'm', '[{"belt":"white","label":"Started BJJ","date":"Oct 2025","classes":0,"done":true},{"belt":"white","label":"White — 1st stripe","date":"Feb 2026","classes":25,"done":true,"current":true},{"belt":"white","label":"White — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('hay', 'Hayan K.', 'white', 2, 'adult', 58, 44, 14, 24, 19, 'HK', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Feb 2025","classes":0,"done":true},{"belt":"white","label":"White — 2nd stripe","date":"Nov 2025","classes":40,"done":true,"current":true},{"belt":"white","label":"White — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('bren', 'Brenden', 'blue', 1, 'adult', 175, 135, 40, 45, 40, 'BD', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Mar 2021","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Oct 2023","classes":138,"done":true},{"belt":"blue","label":"Blue — 1st stripe","date":"Sep 2025","classes":168,"done":true,"current":true},{"belt":"blue","label":"Blue — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('mat', 'Matthew', 'white', 3, 'adult', 108, 80, 28, 35, 28, 'MW', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jan 2023","classes":0,"done":true},{"belt":"white","label":"White — 3rd stripe","date":"Nov 2025","classes":95,"done":true,"current":true},{"belt":"white","label":"White — 4th stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('abs', 'Abs', 'blue', 2, 'adult', 295, 240, 55, 68, 62, 'AB', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Aug 2020","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Feb 2023","classes":170,"done":true},{"belt":"blue","label":"Blue — 2nd stripe","date":"Feb 2026","classes":285,"done":true,"current":true},{"belt":"blue","label":"Blue — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('loon', 'Loong', 'white', 2, 'adult', 72, 55, 17, 30, 24, 'LO', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Apr 2024","classes":0,"done":true},{"belt":"white","label":"White — 2nd stripe","date":"Jan 2026","classes":55,"done":true,"current":true},{"belt":"white","label":"White — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('nko', 'Nicko', 'white', 1, 'adult', 18, 14, 4, 18, 14, 'NK', false, 'm', '[{"belt":"white","label":"Started BJJ","date":"Feb 2026","classes":0,"done":true},{"belt":"white","label":"White — 1st stripe","date":"Mar 2026","classes":14,"done":true,"current":true},{"belt":"white","label":"White — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('gerh', 'Gerhard B.', 'purple', 1, 'adult', 460, 380, 80, 88, 82, 'GB', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jan 2017","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Jun 2019","classes":160,"done":true},{"belt":"purple","label":"Purple belt","date":"Sep 2023","classes":400,"done":true},{"belt":"purple","label":"Purple — 1st stripe","date":"Aug 2025","classes":445,"done":true,"current":true},{"belt":"purple","label":"Purple — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('dam', 'Damien', 'blue', 3, 'adult', 360, 295, 65, 75, 70, 'DM2', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Mar 2019","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Nov 2021","classes":158,"done":true},{"belt":"blue","label":"Blue — 3rd stripe","date":"Apr 2025","classes":342,"done":true,"current":true},{"belt":"blue","label":"Blue — 4th stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('adr', 'Adriano', 'brown', 1, 'adult', 680, 580, 100, 90, 84, 'AR', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jan 2015","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Mar 2017","classes":170,"done":true},{"belt":"purple","label":"Purple belt","date":"Sep 2019","classes":360,"done":true},{"belt":"brown","label":"Brown belt","date":"Jun 2023","classes":580,"done":true},{"belt":"brown","label":"Brown — 1st stripe","date":"Jan 2026","classes":660,"done":true,"current":true},{"belt":"brown","label":"Brown — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('grae', 'Graeme Y.', 'blue', 2, 'adult', 248, 195, 53, 60, 55, 'GY', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jun 2021","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Jan 2024","classes":175,"done":true},{"belt":"blue","label":"Blue — 2nd stripe","date":"Mar 2026","classes":240,"done":true,"current":true},{"belt":"blue","label":"Blue — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('ste', 'Steph L.', 'white', 3, 'adult', 142, 110, 32, 38, 30, 'SL', true, 'f', '[{"belt":"white","label":"Started BJJ","date":"Apr 2023","classes":0,"done":true},{"belt":"white","label":"White — 3rd stripe","date":"Aug 2025","classes":110,"done":true,"current":true},{"belt":"white","label":"White — 4th stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('hug', 'Hugo H.', 'white', 2, 'adult', 65, 50, 15, 26, 20, 'HH', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Mar 2025","classes":0,"done":true},{"belt":"white","label":"White — 2nd stripe","date":"Jan 2026","classes":48,"done":true,"current":true},{"belt":"white","label":"White — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('sax', 'Saxon', 'blue', 1, 'adult', 198, 155, 43, 50, 45, 'SX', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Oct 2021","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Apr 2024","classes":155,"done":true},{"belt":"blue","label":"Blue — 1st stripe","date":"Jan 2026","classes":190,"done":true,"current":true},{"belt":"blue","label":"Blue — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('benv', 'Ben V.', 'white', 4, 'adult', 118, 88, 30, 36, 30, 'BV', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jun 2022","classes":0,"done":true},{"belt":"white","label":"White — 4th stripe","date":"Sep 2025","classes":108,"done":true,"current":true},{"belt":"blue","label":"Blue belt","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('dan', 'Dan', 'blue', 3, 'adult', 380, 300, 80, 78, 70, 'DR', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jun 2020","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Dec 2022","classes":180,"done":true},{"belt":"blue","label":"Blue — 3rd stripe","date":"Aug 2025","classes":360,"done":true,"current":true},{"belt":"blue","label":"Blue — 4th stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('mar', 'Martin', 'brown', 2, 'adult', 820, 700, 120, 95, 88, 'MV', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Jan 2016","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Jun 2018","classes":180,"done":true},{"belt":"purple","label":"Purple belt","date":"Sep 2020","classes":380,"done":true},{"belt":"brown","label":"Brown belt","date":"Mar 2024","classes":720,"done":true},{"belt":"brown","label":"Brown — 2nd stripe","date":"Nov 2025","classes":800,"done":true,"current":true},{"belt":"brown","label":"Brown — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('agl', 'Agustin P.', 'blue', 1, 'adult', 168, 130, 38, 42, 38, 'AG', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"May 2021","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Dec 2023","classes":132,"done":true},{"belt":"blue","label":"Blue — 1st stripe","date":"Aug 2025","classes":160,"done":true,"current":true},{"belt":"blue","label":"Blue — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('jsh', 'Josh C.', 'blue', 2, 'adult', 285, 225, 60, 65, 59, 'JC2', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Mar 2020","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Nov 2022","classes":168,"done":true},{"belt":"blue","label":"Blue — 2nd stripe","date":"Oct 2025","classes":272,"done":true,"current":true},{"belt":"blue","label":"Blue — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('dio', 'Diogo M.', 'purple', 1, 'adult', 480, 400, 80, 90, 85, 'DM3', true, 'm', '[{"belt":"white","label":"Started BJJ","date":"Mar 2019","classes":0,"done":true},{"belt":"blue","label":"Blue belt","date":"Jun 2021","classes":120,"done":true},{"belt":"purple","label":"Purple belt","date":"Apr 2024","classes":420,"done":true},{"belt":"purple","label":"Purple — 1st stripe","date":"Jan 2026","classes":460,"done":true,"current":true},{"belt":"purple","label":"Purple — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('jon', 'Jonathan C.', 'white', 2, 'adult', 52, 40, 12, 22, 18, 'JN', true, 'm', '[{"belt":"white","label":"Transferred from France","date":"Nov 2025","classes":null,"done":true,"xfer":true,"prev":"BJJ Club Lyon"},{"belt":"white","label":"Joined myBJJ","date":"Nov 2025","classes":0,"done":true},{"belt":"white","label":"White — 2nd stripe","date":"Mar 2026","classes":18,"done":true,"current":true},{"belt":"white","label":"White — 3rd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('liam_k', 'Liam W.', 'grey', 2, 'kids', 45, 45, 0, 22, 22, 'LW', true, 'm', '[{"belt":"white","label":"Started Junior BJJ","date":"Feb 2025","classes":0,"done":true},{"belt":"grey","label":"Grey belt","date":"Jul 2025","classes":28,"done":true},{"belt":"grey","label":"Grey — 2nd stripe","date":"Jan 2026","classes":40,"done":true,"current":true},{"belt":"yellow","label":"Yellow belt","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('emma_k', 'Emma T.', 'white', 3, 'kids', 38, 38, 0, 18, 18, 'ET', true, 'f', '[{"belt":"white","label":"Started Junior BJJ","date":"Mar 2025","classes":0,"done":true},{"belt":"white","label":"White — 3rd stripe","date":"Jan 2026","classes":32,"done":true,"current":true},{"belt":"grey","label":"Grey belt","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('noah_k', 'Noah P.', 'yellow', 1, 'kids', 80, 80, 0, 25, 25, 'NP', true, 'm', '[{"belt":"white","label":"Started Junior BJJ","date":"Jun 2023","classes":0,"done":true},{"belt":"grey","label":"Grey belt","date":"Dec 2023","classes":30,"done":true},{"belt":"yellow","label":"Yellow belt","date":"Sep 2024","classes":62,"done":true},{"belt":"yellow","label":"Yellow — 1st stripe","date":"Feb 2026","classes":78,"done":true,"current":true},{"belt":"yellow","label":"Yellow — 2nd stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('oli_k', 'Oliver K.', 'grey', 1, 'kids', 22, 22, 0, 12, 12, 'OK', true, 'm', '[{"belt":"white","label":"Started Junior BJJ","date":"Oct 2025","classes":0,"done":true},{"belt":"grey","label":"Grey belt","date":"Feb 2026","classes":20,"done":true,"current":true},{"belt":"grey","label":"Grey — 1st stripe","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb')),
  ('zoe_k', 'Zoe R.', 'white', 2, 'kids', 44, 44, 0, 18, 18, 'ZR', true, 'f', '[{"belt":"white","label":"Started Junior BJJ","date":"Apr 2025","classes":0,"done":true},{"belt":"white","label":"White — 2nd stripe","date":"Dec 2025","classes":36,"done":true,"current":true},{"belt":"grey","label":"Grey belt","date":null,"classes":null,"done":false}]', '[]', (select id from public.units where legacy_id='nb'))
on conflict (legacy_id) do update set
  full_name=excluded.full_name, belt=excluded.belt, degree=excluded.degree,
  prog=excluded.prog, total=excluded.total, gi_classes=excluded.gi_classes,
  nogi_classes=excluded.nogi_classes, grade=excluded.grade, gi_grade=excluded.gi_grade,
  initials=excluded.initials, has_gi=excluded.has_gi, gender=excluded.gender,
  journey=excluded.journey, feedback=excluded.feedback, unit_id=excluded.unit_id;

-- 4) Promotions (depends on students + units)
insert into public.promotions (legacy_id, student_id, from_belt, to_belt, from_deg, to_deg, type, is_new_belt, date, student_name, promoted_by_name, unit_id) values
  ('pl1', (select id from public.students where legacy_id='dio'), 'purple', 'purple', 0, 1, 'stripe', false, '2026-01-15', 'Diogo M.', 'Prof. Mario', (select id from public.units where legacy_id='nb')),
  ('pl2', (select id from public.students where legacy_id='aar'), 'purple', 'purple', 1, 2, 'stripe', false, '2026-01-15', 'Aaron', 'Prof. Mario', (select id from public.units where legacy_id='nb')),
  ('pl3', (select id from public.students where legacy_id='lia'), 'white', 'white', 3, 4, 'stripe', false, '2026-02-10', 'Liam G.', 'Prof. Felipe', (select id from public.units where legacy_id='nb')),
  ('pl4', (select id from public.students where legacy_id='benv'), 'white', 'white', 3, 4, 'stripe', false, '2026-02-10', 'Ben V.', 'Prof. Felipe', (select id from public.units where legacy_id='nb')),
  ('pl5', (select id from public.students where legacy_id='grae'), 'blue', 'blue', 1, 2, 'stripe', false, '2026-03-08', 'Graeme Y.', 'Prof. Mario', (select id from public.units where legacy_id='nb')),
  ('pl6', (select id from public.students where legacy_id='abs'), 'blue', 'blue', 1, 2, 'stripe', false, '2026-03-08', 'Abs', 'Prof. Mario', (select id from public.units where legacy_id='nb')),
  ('pl7', (select id from public.students where legacy_id='ben'), 'white', 'white', 0, 1, 'stripe', false, '2026-03-20', 'Benji', 'Prof. Mario', (select id from public.units where legacy_id='nb'))
on conflict (legacy_id) do update set
  student_id=excluded.student_id, from_belt=excluded.from_belt,
  to_belt=excluded.to_belt, from_deg=excluded.from_deg, to_deg=excluded.to_deg,
  type=excluded.type, is_new_belt=excluded.is_new_belt, date=excluded.date,
  student_name=excluded.student_name, promoted_by_name=excluded.promoted_by_name,
  unit_id=excluded.unit_id;

-- 5) Events (depends on nothing — legacy_id arrays only)
insert into public.events (legacy_id, title, date, date_text, type, description, link, competing_legacy_ids, supporting_legacy_ids, unit_legacy_ids) values
  ('e1', 'Grappling Industries', '2026-03-22'::date, '22 Mar 2026', 'competition', 'Brock, Jack and Diggaj competing. Come support the team!', '', '{"jac","dan","dig"}'::text[], '{"ff","lia"}'::text[], '{"nb"}'::text[]),
  ('e2', 'Sydney Cup MMA Grappling', '2026-03-28'::date, '28-29 Mar 2026', 'competition', 'Open registration. Great comp for all levels.', 'https://aus-grappling-federation.smoothcomp.com/en/event/28312', '{"mar","dan"}'::text[], '{"eri"}'::text[], '{"nb"}'::text[]),
  ('e3', 'Pacheco vs myBJJ', '2026-04-25'::date, '25 Apr 2026', 'social', 'Porrada Club. Brazilian Cultural Centre, 142 Victoria Rd Marrickville. 2pm start.', '', '{"ff","jam"}'::text[], '{"adm","anna","lia"}'::text[], '{"nb"}'::text[]),
  ('e4', 'NSWBJJF Autumn Cup', '2026-05-24'::date, '24 May 2026', 'competition', 'Season highlight. Register early via SmoothComp.', 'https://smoothcomp.com/event/30587', '{"dio","jac"}'::text[], '{}'::text[], '{"nb"}'::text[]),
  ('e5', 'Subversion XX', '2026-07-25'::date, '25 Jul 2026', 'social', 'Annual team event. Details TBC.', '', '{}'::text[], '{}'::text[], '{"nb"}'::text[])
on conflict (legacy_id) do update set
  title=excluded.title, date=excluded.date, date_text=excluded.date_text,
  type=excluded.type, description=excluded.description, link=excluded.link,
  competing_legacy_ids=excluded.competing_legacy_ids,
  supporting_legacy_ids=excluded.supporting_legacy_ids,
  unit_legacy_ids=excluded.unit_legacy_ids;

-- 6) Programme weeks (depends on units)
insert into public.programme_weeks (legacy_id, week_start, week_index, theme, color, programs, stand_up, ground, notes, unit_id) values
  ('sched_w1', '2026-01-05'::date, 1, 'Closed Guard', '#1A5DAD', '{"Fundamentals","Mixed","Advanced","Junior"}'::text[], '[{"t":"Te-Waza (Arm Throws)","video":""},{"t":"Koshi-Waza (Hip Throws)","video":"https://www.youtube.com/watch?v=dQw4w9WgXcQ"},{"t":"Ashi-Waza (Leg Sweeps)","video":""},{"t":"Sutemi-Waza (Sacrifice Throws)","video":""}]', '[{"t":"Guard — Armbar","video":""},{"t":"Guard — Triangle Choke","video":""},{"t":"Guard — Guillotine","video":""},{"t":"Hip Escape (Shrimp)","video":""}]', 'Revision week. Entry to throws from clinch. Ground focus: attack sequences from closed guard.', (select id from public.units where legacy_id='nb')),
  ('sched_w2', '2026-01-12'::date, 2, 'Guard Passing', '#7e22ce', '{"Fundamentals","Mixed","Advanced"}'::text[], '[{"t":"Uchi-Mata (Inner Thigh Throw)","video":""},{"t":"O-Uchi-Gari (Major Inner Reap)","video":""},{"t":"Ko-Uchi-Gari (Minor Inner Reap)","video":""}]', '[{"t":"Torreando Pass","video":""},{"t":"Knee Slice Pass","video":""},{"t":"Stack Pass","video":""},{"t":"Leg Weave","video":""}]', 'Maintain posture throughout. Drill each pass 10 reps each side. Beginners: torreando only.', (select id from public.units where legacy_id='nb')),
  ('sched_w3', '2026-01-19'::date, 3, 'Takedowns — Revision', '#b45309', '{"Fundamentals","Mixed","Advanced","Junior"}'::text[], '[{"t":"Single Leg Takedown","video":""},{"t":"Double Leg Takedown","video":""},{"t":"O-Goshi (Hip Throw)","video":""},{"t":"De-Ashi-Barai (Foot Sweep)","video":""}]', '[{"t":"Side Control — Maintaining Position","video":""},{"t":"Side Control — Kimura","video":""},{"t":"Mount — Americana","video":""},{"t":"Mount — Armbar","video":""}]', 'Revision of all standing techniques this month. Ground: dominant positions and fundamental submissions.', (select id from public.units where legacy_id='nb')),
  ('sched_w4', '2026-01-26'::date, 4, 'Back Control', '#15803d', '{"Mixed","Advanced"}'::text[], '[{"t":"Back Take from Clinch","video":""},{"t":"Suplex Entry","video":""}]', '[{"t":"Taking the Back from Guard","video":""},{"t":"Rear Naked Choke (RNC)","video":""},{"t":"Body Lock — Back Control","video":""},{"t":"Seat Belt Grip","video":"https://www.instagram.com/mybjj"}]', 'Back control is the highest value position in BJJ. Focus on RNC finish and body lock entries.', (select id from public.units where legacy_id='nb'))
on conflict (legacy_id) do update set
  week_start=excluded.week_start, week_index=excluded.week_index,
  theme=excluded.theme, color=excluded.color, programs=excluded.programs,
  stand_up=excluded.stand_up, ground=excluded.ground, notes=excluded.notes,
  unit_id=excluded.unit_id;

